version: "3.7"
services:
  api:
    image: data-export-api
    build: ./api
    container_name: api
    ports:
      - "9501:9501"
    volumes:
      - ./api:/home
    working_dir: /home
    restart: always
    command: php bin/hyperf.php start
  web:
    image: node:14
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/home
    working_dir: /home
    restart: always
    command:
      - /bin/bash
      - -c
      - |
        yarn
        yarn start